version: '3.4'
services:
 qdd:
  image: berserker5000/curator:latest
  volumes:
   - type: volume
     source: qdd
     target: /usr/local/bin/curator/
  environment:
   CRON_SCHEDULE: "*/2 * * * *"


volumes:
 qdd:
  driver: local
  driver_opts:
   type: "nfs"
   o: addr=172.28.27.210,nolock,soft,rw,vers=4.0
   device: :/mnt/Data/nfsshare/curator/qdd
